---
# Pass in a comma-separated list of repos to use (e.g. "remi,epel").
php_enablerepo: ""
php_memory_limit: "256M"
php_max_execution_time: "60"
php_upload_max_filesize: "64M"
php_apc_cache_by_default: "1"
php_apc_shm_size: "96M"
php_date_timezone: "Europe/Paris"
php_enable_php_fpm: true

php_conf_basepath: /etc/php5

php_conf_files:
  - { name: php.ini, dest: /cli }
  - { name: apc.ini, dest: /mods-available }

php_mods:
  - { name: apc.ini, dest: /cli,     size: 20 }

php_packages:
  - php5
  - php5-fpm
  - php5-mysql
  - php5-pgsql
  - php5-mcrypt
  - php5-cli
  - php5-common
  - php5-curl
  - php5-dev
  - php5-gd
  - php5-ldap
  - php-apc
  - php5-sqlite

php_webserver_daemon: "nginx"
